// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTnA4vKXLlNqEECZYvKsXWpk4FNdUf0A',
    appId: '1:1078818242368:android:7f4751db02c3c1a44204a5',
    messagingSenderId: '1078818242368',
    projectId: 'presence4',
    storageBucket: 'presence4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoyG-Lo5m6eytNs-W8slYfU6St7Ya8wrQ',
    appId: '1:1078818242368:ios:c2acd64b30fe79214204a5',
    messagingSenderId: '1078818242368',
    projectId: 'presence4',
    storageBucket: 'presence4.appspot.com',
    iosClientId: '1078818242368-2jru0iov527qphajd7rvv55698kt8vm5.apps.googleusercontent.com',
    iosBundleId: 'com.lembayung.flutterPresence4',
  );
}
